language: generic
sudo: false
addons:
  apt:
    packages:
    - luarocks
before_install:
  - luarocks install --local luacheck
matrix:
  allow_failures:
  - name: "beauty check"
    env: CONFIG=.luacheck_tidy
  include:
  - name: "health check"
    env: CONFIG=.luacheckrc
script: 
- $HOME/.luarocks/bin/luacheck --config $CONFIG .
notifications:
  email:
    on_failure: change
