language: generic
sudo: false
addons:
  apt:
    packages:
    - luarocks
before_install:
  - luarocks install --local luacheck
env:
  - CONFIG=.luacheckrc
  - CONFIG=.luacheck_tidy
matrix:
  allow_failures:
  - name: "beauty check"
    env: CONFIG=.luacheck_tidy
script: 
- $HOME/.luarocks/bin/luacheck --config $CONFIG .
notifications:
  email:
    on_failure: change
